name: fruit_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^5.6.6
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dots_indicator: ^4.0.1
  equatable: ^2.0.7
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_facebook_auth: ^7.1.1
  flutter_localization: ^0.3.2
  flutter_paypal_payment: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  flutter_svg_provider: ^1.0.7
  get_it: ^8.0.3
  google_sign_in: ^6.3.0
  intl_utils: ^2.8.10
  modal_progress_hud_nsn: ^0.5.1
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  skeletonizer: ^1.4.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
flutter_intl:
  enabled: true
