// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-dA0OjOgrEO-2h0pyP5UYLHYn9Tzv8Q',
    appId: '1:644928734954:web:c6a85fd534967fab713993',
    messagingSenderId: '644928734954',
    projectId: 'fruit-hub-c7113',
    authDomain: 'fruit-hub-c7113.firebaseapp.com',
    storageBucket: 'fruit-hub-c7113.firebasestorage.app',
    measurementId: 'G-WL03X8JX4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOdcUJ8VU6kKRMWRRxgSEI8LuPRGNKCM0',
    appId: '1:644928734954:android:db78f2feb8f411a8713993',
    messagingSenderId: '644928734954',
    projectId: 'fruit-hub-c7113',
    storageBucket: 'fruit-hub-c7113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7-eD8kaqYSBuVjkGYpVfmrencRCK7X2M',
    appId: '1:644928734954:ios:3a41ad47edb0cd85713993',
    messagingSenderId: '644928734954',
    projectId: 'fruit-hub-c7113',
    storageBucket: 'fruit-hub-c7113.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7-eD8kaqYSBuVjkGYpVfmrencRCK7X2M',
    appId: '1:644928734954:ios:3a41ad47edb0cd85713993',
    messagingSenderId: '644928734954',
    projectId: 'fruit-hub-c7113',
    storageBucket: 'fruit-hub-c7113.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt-dA0OjOgrEO-2h0pyP5UYLHYn9Tzv8Q',
    appId: '1:644928734954:web:64670030ec960c8a713993',
    messagingSenderId: '644928734954',
    projectId: 'fruit-hub-c7113',
    authDomain: 'fruit-hub-c7113.firebaseapp.com',
    storageBucket: 'fruit-hub-c7113.firebasestorage.app',
    measurementId: 'G-8Q2H5CZM1E',
  );
}
